/* The file-sharing web page (see devos_fileshare.h): plain HTML + JS, no
 * external files. Names are always inserted as text, never as HTML. */

const char devos_fileshare_page[] =
    "<!doctype html>\n"
    "<html lang='en'>\n"
    "<head>\n"
    "<meta charset='utf-8'>\n"
    "<meta name='viewport' content='width=device-width,initial-scale=1'>\n"
    "<link rel='icon' href='data:,'>\n"
    "<title>devOS SD card</title>\n"
    "<style>\n"
    ":root{--bg:#121417;--sf:#1a1d24;--sa:#242933;--bd:#2e384d;--tx:#eceff4;--mu:#9aa5b8;--ac:#00e5ff;--ok:#00e676;--wa:#ffb300;--dg:#ff5252;color-scheme:dark}\n"
    "@media (prefers-color-scheme:light){:root{--bg:#f8fafc;--sf:#fff;--sa:#f1f5f9;--bd:#cbd5e1;--tx:#0f172a;--mu:#475569;--ac:#2563eb;--ok:#0d9488;--wa:#d97706;--dg:#dc2626;color-scheme:light}}\n"
    "*{box-sizing:border-box}\n"
    "body{margin:0;background:var(--bg);color:var(--tx);font:15px/1.4 system-ui,-apple-system,Segoe UI,Roboto,sans-serif}\n"
    "header{display:flex;align-items:baseline;gap:12px;padding:14px 20px;border-bottom:1px solid var(--bd);background:var(--sf)}\n"
    "header b{color:var(--ac);font-size:18px}\n"
    "#free{margin-left:auto;color:var(--mu);font-size:13px}\n"
    "main{max-width:1000px;margin:0 auto;padding:16px 20px 60px}\n"
    "#crumbs{font-size:17px;margin:4px 0 14px;word-break:break-all}\n"
    "#crumbs a{color:var(--ac);text-decoration:none}\n"
    "#crumbs a:hover{text-decoration:underline}\n"
    "#crumbs span{color:var(--mu);margin:0 6px}\n"
    ".bar{display:flex;flex-wrap:wrap;gap:8px;align-items:center;margin-bottom:12px}\n"
    "button{font:inherit;color:var(--tx);background:var(--sa);border:1px solid var(--bd);border-radius:6px;padding:7px 14px;cursor:pointer}\n"
    "button:hover,button:focus-visible{border-color:var(--ac);outline:none}\n"
    "button.pri{background:var(--ac);color:var(--bg);border-color:var(--ac);font-weight:600}\n"
    "button.sm{padding:3px 9px;font-size:13px}\n"
    "button.dg:hover,button.dg:focus-visible{border-color:var(--dg);color:var(--dg)}\n"
    "label{color:var(--mu);font-size:14px;margin-left:auto;cursor:pointer}\n"
    "#drop{border:2px dashed var(--bd);border-radius:8px;padding:14px;text-align:center;color:var(--mu);margin-bottom:12px}\n"
    "#drop.on{border-color:var(--ac);color:var(--ac);background:var(--sa)}\n"
    "#msg{min-height:1.4em;margin:0 0 8px;color:var(--dg)}\n"
    "#msg.ok{color:var(--ok)}\n"
    ".up{display:flex;gap:10px;align-items:center;font-size:13px;color:var(--mu);margin:4px 0}\n"
    ".up .n{flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}\n"
    ".up progress{width:160px;accent-color:var(--ac)}\n"
    "table{width:100%;border-collapse:collapse;background:var(--sf);border:1px solid var(--bd);border-radius:8px;overflow:hidden}\n"
    "th,td{padding:8px 12px;text-align:left;border-bottom:1px solid var(--bd)}\n"
    "th{font-size:12px;letter-spacing:1px;color:var(--mu);font-weight:600;text-transform:uppercase}\n"
    "tr:last-child td{border-bottom:0}\n"
    "tbody tr:hover{background:var(--sa)}\n"
    "td.nm{word-break:break-all}\n"
    "td.nm a{color:var(--tx);text-decoration:none}\n"
    "td.nm a:hover{color:var(--ac);text-decoration:underline}\n"
    "td.nm .i{display:inline-block;width:1.6em;color:var(--mu)}\n"
    "td.nm .d{color:var(--ac)}\n"
    "td.sz,td.tm{color:var(--mu);white-space:nowrap;font-size:13px}\n"
    "td.sz{text-align:right}\n"
    "td.ac{white-space:nowrap;text-align:right}\n"
    "td.ac button,td.ac a{margin-left:4px}\n"
    "td.ac a{font-size:13px;color:var(--mu)}\n"
    ".empty{color:var(--mu);text-align:center;padding:24px}\n"
    "@media (max-width:640px){td.tm,th.tm{display:none}main{padding:12px}}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<header><b>devOS</b><span>SD card</span><span id='free'></span></header>\n"
    "<main>\n"
    "<nav id='crumbs'></nav>\n"
    "<div class='bar'>\n"
    "<button class='pri' id='bu'>Upload files</button>\n"
    "<button id='bf'>Upload a folder</button>\n"
    "<button id='bn'>New folder</button>\n"
    "<button id='br'>Refresh</button>\n"
    "<label><input type='checkbox' id='hid'> Show hidden files</label>\n"
    "<input type='file' id='fi' multiple hidden>\n"
    "<input type='file' id='fd' webkitdirectory hidden>\n"
    "</div>\n"
    "<div id='drop'>Drop files or folders here to upload them to this folder</div>\n"
    "<p id='msg'></p>\n"
    "<div id='q'></div>\n"
    "<table><thead><tr><th>Name</th><th class='sz'>Size</th><th class='tm'>Modified</th><th></th></tr></thead><tbody id='tb'></tbody></table>\n"
    "</main>\n"
    "<script>\n"
    "'use strict';\n"
    "const $=id=>document.getElementById(id);\n"
    "const E=encodeURIComponent;\n"
    "let cur='/',items=[];\n"
    "function el(tag,cls,txt){const e=document.createElement(tag);if(cls)e.className=cls;if(txt!=null)e.textContent=txt;return e}\n"
    "function join(d,n){return d==='/'?'/'+n:d+'/'+n}\n"
    "function size(b){if(b<1024)return b+' B';const u=['KB','MB','GB','TB'];let i=-1;do{b/=1024;i++}while(b>=1024&&i<3);return b.toFixed(b<10?1:0)+' '+u[i]}\n"
    "function say(t,ok){const m=$('msg');m.textContent=t||'';m.className=ok?'ok':''}\n"
    "const GONE='The Tab5 isn\\'t answering - is sharing still switched on?';\n"
    "async function call(method,url){\n"
    "  let r;\n"
    "  try{r=await fetch(url,{method:method,headers:{'X-Devos':'1'}})}catch(e){throw new Error(GONE)}\n"
    "  if(r.status===401){location.reload();throw new Error('Sharing restarted: enter the new password')}\n"
    "  if(!r.ok){throw new Error((await r.text()).trim()||r.status+' '+r.statusText)}\n"
    "  return r;\n"
    "}\n"
    "function href(p){return p==='/'?'#':'#'+p.split('/').map(E).join('/')}\n"
    "function go(p){location.hash=href(p)}\n"
    "function fromHash(){let h=location.hash.slice(1);try{h=decodeURIComponent(h)}catch(e){}return h||'/'}\n"
    "async function load(){\n"
    "  cur=fromHash();\n"
    "  try{\n"
    "    const r=await call('GET','/api/list?path='+E(cur));\n"
    "    const j=await r.json();\n"
    "    items=j.entries;\n"
    "    if(j.total)$('free').textContent=size(j.free)+' free of '+size(j.total);\n"
    "    render();\n"
    "  }catch(e){say(e.message);if(cur!=='/')go('/')}\n"
    "}\n"
    "function crumbs(){\n"
    "  const c=$('crumbs');c.textContent='';\n"
    "  const a=el('a',null,'SD card');a.href='#';c.appendChild(a);\n"
    "  let p='';\n"
    "  for(const part of cur.split('/').filter(Boolean)){\n"
    "    p+='/'+part;c.appendChild(el('span',null,'/'));\n"
    "    const b=el('a',null,part);b.href=href(p);c.appendChild(b);\n"
    "  }\n"
    "}\n"
    "function render(){\n"
    "  crumbs();\n"
    "  const tb=$('tb');tb.textContent='';\n"
    "  const show=$('hid').checked;\n"
    "  const list=items.filter(x=>show||x.name[0]!=='.').sort((a,b)=>(b.dir-a.dir)||a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:'base'}));\n"
    "  if(cur!=='/'){\n"
    "    const tr=el('tr');const td=el('td','nm');const a=el('a');\n"
    "    a.appendChild(el('span','i d','\\u2191'));a.appendChild(document.createTextNode('Up a folder'));\n"
    "    a.href=href(cur.slice(0,cur.lastIndexOf('/'))||'/');\n"
    "    td.appendChild(a);tr.appendChild(td);tr.appendChild(el('td'));tr.appendChild(el('td','tm'));tr.appendChild(el('td'));tb.appendChild(tr);\n"
    "  }\n"
    "  if(!list.length){const tr=el('tr');const td=el('td','empty',items.length?'Only hidden files here':'This folder is empty');td.colSpan=4;tr.appendChild(td);tb.appendChild(tr)}\n"
    "  for(const x of list){\n"
    "    const p=join(cur,x.name);\n"
    "    const tr=el('tr');const nm=el('td','nm');const a=el('a');\n"
    "    a.appendChild(el('span',x.dir?'i d':'i',x.dir?'\\u25A0':'\\u25A1'));\n"
    "    a.appendChild(document.createTextNode(x.name));\n"
    "    if(x.dir){a.href=href(p)}else{a.href='/api/file?path='+E(p);a.target='_blank';a.rel='noopener'}\n"
    "    nm.appendChild(a);tr.appendChild(nm);\n"
    "    tr.appendChild(el('td','sz',x.dir?'':size(x.size)));\n"
    "    tr.appendChild(el('td','tm',x.mtime?new Date(x.mtime*1000).toLocaleString():''));\n"
    "    const ac=el('td','ac');\n"
    "    if(!x.dir){const d=el('a',null,'Download');d.href='/api/file?dl=1&path='+E(p);d.setAttribute('download',x.name);ac.appendChild(d)}\n"
    "    const rn=el('button','sm','Rename');rn.onclick=()=>rename(x);ac.appendChild(rn);\n"
    "    const del=el('button','sm dg','Delete');del.onclick=()=>remove(x);ac.appendChild(del);\n"
    "    tr.appendChild(ac);tb.appendChild(tr);\n"
    "  }\n"
    "}\n"
    "async function rename(x){\n"
    "  const n=prompt('New name for '+x.name,x.name);\n"
    "  if(!n||n===x.name)return;\n"
    "  if(n.includes('/')){say('A name can\\'t contain /');return}\n"
    "  try{await call('POST','/api/rename?path='+E(join(cur,x.name))+'&to='+E(join(cur,n)));say('Renamed to '+n,true);load()}catch(e){say(e.message)}\n"
    "}\n"
    "async function remove(x){\n"
    "  if(!confirm(x.dir?'Delete the folder '+x.name+' and everything in it?':'Delete '+x.name+'?'))return;\n"
    "  try{await call('DELETE','/api/file?recursive=1&path='+E(join(cur,x.name)));say('Deleted '+x.name,true);load()}catch(e){say(e.message)}\n"
    "}\n"
    "async function mkdir(){\n"
    "  const n=prompt('Folder name');\n"
    "  if(!n)return;\n"
    "  if(n.includes('/')){say('A name can\\'t contain /');return}\n"
    "  try{await call('POST','/api/mkdir?path='+E(join(cur,n)));say('Made '+n,true);load()}catch(e){say(e.message)}\n"
    "}\n"
    "/* uploads: one at a time, each with a progress bar */\n"
    "let queue=[],busy=false;\n"
    "function put(file,rel,row){\n"
    "  return new Promise((ok,fail)=>{\n"
    "    const x=new XMLHttpRequest();\n"
    "    x.open('PUT','/api/file?path='+E(rel));\n"
    "    x.setRequestHeader('X-Devos','1');\n"
    "    x.upload.onprogress=e=>{if(e.lengthComputable)row.bar.value=e.loaded/e.total};\n"
    "    x.onload=()=>x.status<300?ok():fail(new Error(x.responseText.trim()||x.status+' '+x.statusText));\n"
    "    x.onerror=()=>fail(new Error(GONE));\n"
    "    x.send(file);\n"
    "  });\n"
    "}\n"
    "async function pump(){\n"
    "  if(busy)return;busy=true;\n"
    "  let n=0,bad=0;\n"
    "  while(queue.length){\n"
    "    const job=queue.shift();\n"
    "    try{await put(job.file,job.path,job.row);job.row.div.remove();n++}\n"
    "    catch(e){bad++;job.row.bar.remove();job.row.st.textContent=e.message;job.row.st.style.color='var(--dg)'}\n"
    "  }\n"
    "  busy=false;\n"
    "  if(n)say('Uploaded '+n+' file'+(n>1?'s':'')+(bad?', '+bad+' failed':''),!bad);\n"
    "  load();\n"
    "}\n"
    "function enqueue(files){\n"
    "  if(!files.length)return;\n"
    "  const clash=files.filter(f=>!f.rel.includes('/')&&items.some(x=>!x.dir&&x.name===f.rel)).length;\n"
    "  if(clash&&!confirm('Replace '+clash+' existing file'+(clash>1?'s':'')+'?'))return;\n"
    "  say('');\n"
    "  for(const f of files){\n"
    "    const div=el('div','up');div.appendChild(el('span','n',f.rel+'  ('+size(f.file.size)+')'));\n"
    "    const bar=el('progress');bar.max=1;bar.value=0;div.appendChild(bar);\n"
    "    const st=el('span');div.appendChild(st);$('q').appendChild(div);\n"
    "    queue.push({file:f.file,path:join(cur,f.rel),row:{div:div,bar:bar,st:st}});\n"
    "  }\n"
    "  pump();\n"
    "}\n"
    "function picked(input){\n"
    "  enqueue([...input.files].map(f=>({file:f,rel:f.webkitRelativePath||f.name})));\n"
    "  input.value='';\n"
    "}\n"
    "/* folders dropped on the page: walk them */\n"
    "function walk(entry,path,out){\n"
    "  return new Promise(done=>{\n"
    "    if(entry.isFile){entry.file(f=>{out.push({file:f,rel:path+f.name});done()},()=>done());return}\n"
    "    const rd=entry.createReader(),all=[];\n"
    "    const next=()=>rd.readEntries(async es=>{\n"
    "      if(es.length){all.push(...es);next();return}\n"
    "      for(const e of all)await walk(e,path+entry.name+'/',out);\n"
    "      done();\n"
    "    },()=>done());\n"
    "    next();\n"
    "  });\n"
    "}\n"
    "async function dropped(dt){\n"
    "  const out=[],entries=[...dt.items].map(i=>i.webkitGetAsEntry&&i.webkitGetAsEntry()).filter(Boolean);\n"
    "  if(entries.length){for(const e of entries)await walk(e,'',out)}\n"
    "  else{for(const f of dt.files)out.push({file:f,rel:f.name})}\n"
    "  enqueue(out);\n"
    "}\n"
    "$('bu').onclick=()=>$('fi').click();\n"
    "$('bf').onclick=()=>$('fd').click();\n"
    "$('bn').onclick=mkdir;\n"
    "$('br').onclick=load;\n"
    "$('fi').onchange=e=>picked(e.target);\n"
    "$('fd').onchange=e=>picked(e.target);\n"
    "$('hid').onchange=render;\n"
    "const dz=$('drop');\n"
    "['dragenter','dragover'].forEach(t=>document.addEventListener(t,e=>{e.preventDefault();dz.classList.add('on')}));\n"
    "['dragleave','drop'].forEach(t=>document.addEventListener(t,e=>{e.preventDefault();if(t==='drop'||!e.relatedTarget)dz.classList.remove('on')}));\n"
    "document.addEventListener('drop',e=>dropped(e.dataTransfer));\n"
    "window.onhashchange=()=>{say('');load()};\n"
    "load();\n"
    "</script>\n"
    "</body>\n"
    "</html>\n";
